### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by NikolayS** [dhamaniasad/awesome-postgres#145]
21 PRs are in the queue, collected during many months... 

Many of those PRs are with conflicts and their authors don't seem to respond -- so why not just take those proposals manually? (many seem to be good)

**Comment by dhamaniasad** [comment]
This repo is very much alive. We do have a backlog of PRs that need to be rebased in order to be merged. 

I will keep this issue open, and I will start closing the open PRs and adding the links manually in case they would have been merged. 

Also do note that not all PRs will be accepted immediately, some tools are given more time to mature, some PRs are kept open for more community backing.

**Comment by cbbrowne** [comment]
Do people know that they need to rebase their PRs?  It's probably apropos to toss them back so their owners know that they need to do some rework.

**Comment by dhamaniasad** [comment]
@cbbrowne Thanks for reminding me about this. I'm going to get to this tomorrow and send out messages to all pending PR authors, and rebase myself in case of no response.
